# Generated by Django 4.1.7 on 2023-03-08 05:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210421_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_bg',
            field=sorl.thumbnail.fields.ImageField(default='default-bg.jpg', upload_to='profiles'),
        ),
    ]
